### PR TITLE
Temporary demo user accounts

### LINKED ISSUE #108: create temporary user functionality for demo purposes
account should self destruct after an hour. 

users should be warned and given the option to email admin for a permanent account

### PR DESCRIPTION
**Pull request by macfarlandian**
closes #108

### CODE REVIEW

**Comment by macfarlandian** [comment]
@salspaugh right now it preloads the two FAA datasets we were using for testing ... if you want to swap those for something else let me know. otherwise this should be ready for your review.

**Comment by macfarlandian** [comment]
hold that, something seems to be wrong with the "time" datatypes ... investigating

**Comment by macfarlandian** [comment]
OK that problem is fixed and I also made a better self-destruct timer bc I realized my old one wasn't working

**Comment by salspaugh** [comment]
Sorry for the delay on reviewing this! I will look at it today.

**Comment by salspaugh** [comment]
This looks great! I think it's good to merge. I have a few other datasets we could include if we wanted, though I don't feel strongly. I imagine Marti would feel strongly? Have you gotten a chance to meet with her and show her the latest?

**Pull request merged**
